### ISSUE TITLE
Group/covariates spreadsheet

### ISSUE THREAD

**Issue by YaraToenders** [mindandbrain/halfpipe#3]
Hi Lea,

When specifying the group level statistics I get an error when I try to use a csv file with the group / covariate information (see attached), but when I convert this file to a text file it works fine. Is a text file the preferred format?

With the csv file, it seems like it cannot read the header of the file (there is also a screenshot of the file attached), as it gives the error {'name': [Not a valid string.']}. The column names above do not match the column names in the file, whereas when a text file is used, the column names are correct. Do you have any ideas on why this could be the case? Please let me know if anything is unclear.

![Screenshot_csvfile](https://user-images.githubusercontent.com/45774325/94084490-03521480-fe49-11ea-8376-4ec5d4d17884.JPG)
![Screenshot_error](https://user-images.githubusercontent.com/45774325/94084494-064d0500-fe49-11ea-9efa-25c944b60cf5.JPG)

**Comment by HippocampusGirl** [comment]
Dear Yara,

Thank you for the error report!

I copied down the screenshot of the CSV file above:

```
ID,Age,Sex,Group,Severity
C001,20,1,Dep,21
C002,20,2,Dep,13
C003,20,1,Dep,34
C004,20,2,Dep,24
C005,20,1,Dep,20
C006,20,2,Dep,28
C007,20,1,Dep,22
C008,20,2,Dep,25
C009,20,1,Dep,27
C010,20,2,Dep,12
C011,20,1,Dep,12
C012,20,2,Dep,28
C013,20,1,Dep,28
C014,20,,Dep,29
C015,20,1,Dep,25
C016,20,,Dep,26
C017,20,1,Dep,28
C018,20,2,Dep,22
C019,20,1,Dep,21
C020,20,2,Dep,22
C021,20,1,HC,11
C022,20,2,HC,9
```

With this file, I cannot replicate the error. Halfpipe works as expected, and shows the column names for me.

Could you send me the full file for debugging?

**Comment by YaraToenders** [comment]
Thank you for looking at it. See below for the file. I had to zip it to upload it here, but used the unzipped version in the pipeline.
[SAD_groups.csv.zip](https://github.com/mindandbrain/Halfpipe/files/5295350/SAD_groups.csv.zip)

**Comment by HippocampusGirl** [comment]
Hi Yara, 

thank you for the file! 

Turns out that the file was saved with an invisible special ("unicode") character at the beginning to help text editors detect the encoding. 
This special character was confusing the function that I wrote to detect if a CSV file has a header or not.

I changed the code to blindly remove all non-latin characters before checking for a header, as there is a big variety to these [invisible marks](https://unicodebook.readthedocs.io/unicode_encodings.html#bom).
This may lead to issues further down the line if a user's column names were to be, for example, all Cyrillic, Arabic, or Chinese characters. However, I don't think there are any researchers that would do that. What do you think? 

Best,
Lea

**Comment by YaraToenders** [comment]
Thanks Lea, sounds like a perfect solution.

**Comment by YaraToenders** [comment]
**What happened?**
I used a txt file with the group information (not the same computer as last time - so it might be something I'm doing wrong) and did not load it, but instead gave an error. 

**Is there an error message?**
See below and attached:
[err.txt](https://github.com/mindandbrain/Halfpipe/files/5349108/err.txt)
[groups.txt](https://github.com/mindandbrain/Halfpipe/files/5349113/groups.txt)

[2020-10-09 02:37:58,0143] [halfpipe.ui     ] [ERROR    ] Exception: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
│ Traceback (most recent call last):
│   File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/ui/model/spreadsheet.py", line 183, in run
│     loadspreadsheet(self.filepath)
│   File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/io/file/spreadsheet.py", line 73, in loadspreadsheet
│     return pd.DataFrame(loadmatrix(fname))
│   File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/io/file/spreadsheet.py", line 107, in loadmatrix
│     return loadmatrix(in_file, dtype=dtype, comments="/")
│   File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/io/file/spreadsheet.py", line 108, in loadmatrix
│     raise exception
│   File "/usr/local/miniconda/lib/python3.7/site-packages/halfpipe/io/file/spreadsheet.py", line 101, in loadmatrix
│     in_array = np.genfromtxt(in_file, delimiter=",", skip_header=1, **kwargs)
│   File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1718, in genfromtxt
│     next(fhd)
│   File "/usr/local/miniconda/lib/python3.7/codecs.py", line 322, in decode
│     (result, consumed) = self._buffer_decode(data, self.errors, final)
└─UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**What is the exact command that you used to run `Halfpipe`?**
singularity run --no-home --cleanenv --bind /:/ext /data/scratch/projects/punim0564/Halfpipe_1.0.0b4.sif --only-spec-ui

**Comment by HippocampusGirl** [comment]
Dear Yara, 

I fixed this issue just now. 

Your file is encoded with the "UTF-16" standard, instead of the "UTF-8" one that Python uses by default. This means that the sequence of bytes used to represent letters and numbers is slightly different than what Python expects. 

I added some code to detect the encoding of files using the package (chardet)[https://github.com/chardet/chardet], and so far it seems to work :-)

I will send around a new version tomorrow so you can test it.
